package com.millionaire.game.audio

import android.app.Activity
import android.app.Application
import android.content.Context
import android.content.SharedPreferences
import android.media.AudioAttributes
import android.media.AudioFocusRequest
import android.media.AudioManager
import android.media.MediaPlayer
import android.media.SoundPool
import android.os.Build
import android.os.Bundle
import android.util.Log
import androidx.annotation.RawRes
import com.millionaire.game.R

/**
 * Application-wide audio engine: looping background music plus low-latency sound
 * effects.
 *
 * - Effects are preloaded into a [SoundPool] so they fire instantly on tap.
 * - Music plays through a looping [MediaPlayer] (one track at a time).
 * - Music pauses automatically when the whole app goes to the background and
 *   resumes on return, and it ducks/pauses politely when another app takes audio
 *   focus.
 *
 * Activities declare which music bed they want by implementing [BgmHost]; the
 * engine switches tracks as the user navigates and never restarts a track that is
 * already playing.
 *
 * The audio assets are generated by `tools/generate-audio.js` and packaged in
 * `res/raw` (see the README). Every entry point is a no-op when a resource is
 * missing, so a bad asset can never crash the game.
 */
object SoundManager {

    private const val TAG = "SoundManager"

    private const val PREFS = "millionaire_audio"
    private const val KEY_MUSIC_ENABLED = "music_enabled"
    private const val KEY_SFX_ENABLED = "sfx_enabled"
    private const val KEY_MUSIC_VOLUME = "music_volume"
    private const val KEY_SFX_VOLUME = "sfx_volume"

    private const val DEFAULT_MUSIC_ENABLED = true
    private const val DEFAULT_SFX_ENABLED = true
    private const val DEFAULT_MUSIC_VOLUME = 0.5f
    private const val DEFAULT_SFX_VOLUME = 0.9f

    /** Volume multiplier while another app is talking over us. */
    private const val DUCK_FACTOR = 0.25f
    private const val MAX_SFX_STREAMS = 4

    /** One-shot sounds. [resId] points at the generated WAV in `res/raw`. */
    enum class Sfx(val resName: String, @RawRes val resId: Int) {
        CLICK("sfx_click", R.raw.sfx_click),
        LOCK("sfx_lock", R.raw.sfx_lock),
        SUSPENSE("sfx_suspense", R.raw.sfx_suspense),
        CORRECT("sfx_correct", R.raw.sfx_correct),
        WRONG("sfx_wrong", R.raw.sfx_wrong),
        LIFELINE("sfx_lifeline", R.raw.sfx_lifeline),
        WIN("sfx_win", R.raw.sfx_win),
        LOSE("sfx_lose", R.raw.sfx_lose),
    }

    /** Looping music beds. */
    enum class BgmTrack(val resName: String, @RawRes val resId: Int) {
        MENU("bgm_menu", R.raw.bgm_menu),
        GAME("bgm_game", R.raw.bgm_game),
    }

    private var application: Application? = null
    private var prefs: SharedPreferences? = null

    private val audioAttributes: AudioAttributes = AudioAttributes.Builder()
        .setUsage(AudioAttributes.USAGE_GAME)
        .setContentType(AudioAttributes.CONTENT_TYPE_MUSIC)
        .build()

    private var soundPool: SoundPool? = null

    /** SoundPool sample id per effect. */
    private val sampleIds = HashMap<Sfx, Int>()
    private val sampleNames = HashMap<Int, Sfx>()
    private val loadedSamples = HashSet<Int>()

    /** Effects requested before their sample finished decoding: id -> volume. */
    private val pendingPlays = HashMap<Int, Float>()

    private var sfxLevel = DEFAULT_SFX_VOLUME
    private var musicLevel = DEFAULT_MUSIC_VOLUME

    private var bgmPlayer: MediaPlayer? = null
    private var bgmTrack: BgmTrack? = null

    /** The bed the current screen wants, remembered across mute/unmute. */
    private var requestedTrack: BgmTrack? = null

    /** Whether music should be sounding; cleared when the user mutes it. */
    private var musicWanted = false

    /** Number of started (visible) activities; 0 means the app is in the background. */
    private var startedActivities = 0

    private var audioFocusHeld = false
    private var focusRequest: AudioFocusRequest? = null
    private var ducked = false

    /** Focus listener for the pre-Android-8 API, which needs a stable instance. */
    private val legacyFocusListener = AudioManager.OnAudioFocusChangeListener { change ->
        onAudioFocusChange(change)
    }

    // ------------------------------------------------------------------ setup

    /** Called once from [com.millionaire.game.MillionaireApp]. */
    fun init(app: Application) {
        if (application != null) return
        application = app
        prefs = app.getSharedPreferences(PREFS, Context.MODE_PRIVATE)

        musicLevel = prefs?.getFloat(KEY_MUSIC_VOLUME, DEFAULT_MUSIC_VOLUME) ?: DEFAULT_MUSIC_VOLUME
        sfxLevel = prefs?.getFloat(KEY_SFX_VOLUME, DEFAULT_SFX_VOLUME) ?: DEFAULT_SFX_VOLUME

        val pool = SoundPool.Builder()
            .setMaxStreams(MAX_SFX_STREAMS)
            .setAudioAttributes(audioAttributes)
            .build()
        pool.setOnLoadCompleteListener { _, sampleId, status ->
            if (status == 0) {
                loadedSamples.add(sampleId)
                val queued = pendingPlays.remove(sampleId)
                if (queued != null) playSample(sampleId, queued)
            } else {
                Log.w(TAG, "SoundPool failed to load ${sampleNames[sampleId]} (status=$status)")
            }
        }
        soundPool = pool

        // Preload everything so the very first tap is not silent.
        Sfx.values().forEach { ensureLoaded(it) }

        app.registerActivityLifecycleCallbacks(lifecycleCallbacks)
    }

    // ---------------------------------------------------------------- effects

    /** Play a one-shot effect, scaled by the user's effects volume. */
    fun playSfx(sfx: Sfx, volume: Float = 1f) {
        if (!isSfxEnabled()) return
        val level = (sfxLevel * volume).coerceIn(0f, 1f)
        if (level <= 0f) return
        val sampleId = ensureLoaded(sfx) ?: return
        if (loadedSamples.contains(sampleId)) {
            playSample(sampleId, level)
        } else {
            pendingPlays[sampleId] = level
        }
    }

    private fun ensureLoaded(sfx: Sfx): Int? {
        sampleIds[sfx]?.let { return it }
        val pool = soundPool ?: return null
        val id = try {
            pool.load(application, sfx.resId, 1)
        } catch (e: Exception) {
            Log.w(TAG, "Could not load ${sfx.resName}", e)
            return null
        }
        if (id == 0) {
            Log.w(TAG, "SoundPool rejected ${sfx.resName}")
            return null
        }
        sampleIds[sfx] = id
        sampleNames[id] = sfx
        return id
    }

    private fun playSample(sampleId: Int, volume: Float) {
        soundPool?.play(sampleId, volume, volume, 1, 0, 1.0f)
    }

    // ------------------------------------------------------------------ music

    /** Switch to [track] (or resume it) unless the user has music turned off. */
    fun playBgm(track: BgmTrack) {
        requestedTrack = track
        musicWanted = true
        if (!isMusicEnabled()) {
            stopBgmInternal()
            return
        }
        if (bgmPlayer != null && bgmTrack == track) {
            applyMusicVolume()
            startPlayerIfPossible()
            return
        }
        releasePlayer()
        val player = createPlayer(track) ?: return
        bgmPlayer = player
        bgmTrack = track
        applyMusicVolume()
        startPlayerIfPossible()
    }

    /** Pause music without forgetting the track (used under the reveal sting). */
    fun pauseForSting() {
        musicWanted = false
        bgmPlayer?.let { if (it.isPlaying) it.pause() }
    }

    /** Undo [pauseForSting]. */
    fun resumeAfterSting() {
        musicWanted = true
        startPlayerIfPossible()
    }

    /** Stop music entirely and unload the track (music turned off). */
    private fun stopBgmInternal() {
        releasePlayer()
    }

    private fun createPlayer(track: BgmTrack): MediaPlayer? {
        val app = application ?: return null
        return try {
            val player = MediaPlayer()
            player.setAudioAttributes(audioAttributes)
            val afd = app.resources.openRawResourceFd(track.resId)
            if (afd != null) {
                afd.use { player.setDataSource(it.fileDescriptor, it.startOffset, it.length) }
                player.prepare()
            } else {
                // Should not happen: WAVs are kept uncompressed (see app/build.gradle).
                Log.w(TAG, "${track.resName} is not streamable from resources")
                player.release()
                return null
            }
            player.isLooping = true
            player.setOnErrorListener { _, what, extra ->
                Log.w(TAG, "MediaPlayer error (what=$what extra=$extra)")
                true
            }
            player
        } catch (e: Exception) {
            Log.w(TAG, "Could not prepare ${track.resName}", e)
            null
        }
    }

    private fun startPlayerIfPossible() {
        val player = bgmPlayer ?: return
        if (!musicWanted || startedActivities == 0 || !isMusicEnabled()) return
        if (!requestAudioFocus()) return
        if (!player.isPlaying) {
            try {
                player.start()
            } catch (e: IllegalStateException) {
                Log.w(TAG, "Could not start music", e)
            }
        }
    }

    private fun applyMusicVolume() {
        val level = if (ducked) musicLevel * DUCK_FACTOR else musicLevel
        bgmPlayer?.setVolume(level, level)
    }

    private fun releasePlayer() {
        bgmPlayer?.let { player ->
            try {
                if (player.isPlaying) player.stop()
            } catch (_: IllegalStateException) {
                // already stopped
            }
            player.reset()
            player.release()
        }
        bgmPlayer = null
        bgmTrack = null
        abandonAudioFocus()
    }

    // ------------------------------------------------------------- lifecycle

    private val lifecycleCallbacks = object : Application.ActivityLifecycleCallbacks {

        override fun onActivityStarted(activity: Activity) {
            startedActivities++
            if (startedActivities == 1) startPlayerIfPossible()
        }

        /** Each activity declares its own music bed via [BgmHost]. */
        override fun onActivityResumed(activity: Activity) {
            (activity as? BgmHost)?.let { playBgm(it.bgmTrack) }
        }

        override fun onActivityStopped(activity: Activity) {
            startedActivities = (startedActivities - 1).coerceAtLeast(0)
            // Only silence the music once the whole app has left the foreground,
            // so navigating between activities never interrupts playback.
            if (startedActivities == 0) {
                bgmPlayer?.let { if (it.isPlaying) it.pause() }
            }
        }

        override fun onActivityCreated(activity: Activity, savedInstanceState: Bundle?) = Unit
        override fun onActivityPaused(activity: Activity) = Unit
        override fun onActivitySaveInstanceState(activity: Activity, outState: Bundle) = Unit
        override fun onActivityDestroyed(activity: Activity) = Unit
    }

    // ----------------------------------------------------------- audio focus

    private fun requestAudioFocus(): Boolean {
        if (audioFocusHeld) return true
        val app = application ?: return true
        val manager = app.getSystemService(Context.AUDIO_SERVICE) as? AudioManager ?: return true
        val granted = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val request = focusRequest ?: AudioFocusRequest.Builder(AudioManager.AUDIOFOCUS_GAIN)
                .setAudioAttributes(audioAttributes)
                .setOnAudioFocusChangeListener { change -> onAudioFocusChange(change) }
                .setWillPauseWhenDucked(false)
                .build()
                .also { focusRequest = it }
            manager.requestAudioFocus(request) == AudioManager.AUDIOFOCUS_REQUEST_GRANTED
        } else {
            @Suppress("DEPRECATION")
            manager.requestAudioFocus(
                legacyFocusListener,
                AudioManager.STREAM_MUSIC,
                AudioManager.AUDIOFOCUS_GAIN
            ) == AudioManager.AUDIOFOCUS_REQUEST_GRANTED
        }
        audioFocusHeld = granted
        if (!granted) Log.w(TAG, "Audio focus denied; music stays paused")
        return granted
    }

    private fun abandonAudioFocus() {
        if (!audioFocusHeld) return
        val app = application ?: return
        val manager = app.getSystemService(Context.AUDIO_SERVICE) as? AudioManager ?: return
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            focusRequest?.let { manager.abandonAudioFocusRequest(it) }
        } else {
            @Suppress("DEPRECATION")
            manager.abandonAudioFocus(legacyFocusListener)
        }
        audioFocusHeld = false
    }

    private fun onAudioFocusChange(focusChange: Int) {
        when (focusChange) {
            AudioManager.AUDIOFOCUS_GAIN -> {
                audioFocusHeld = true
                ducked = false
                applyMusicVolume()
                startPlayerIfPossible()
            }
            AudioManager.AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK -> {
                ducked = true
                applyMusicVolume()
            }
            AudioManager.AUDIOFOCUS_LOSS_TRANSIENT,
            AudioManager.AUDIOFOCUS_LOSS -> {
                // Keep musicWanted: resuming the app (or regaining focus) brings it back.
                audioFocusHeld = false
                ducked = false
                bgmPlayer?.let { if (it.isPlaying) it.pause() }
            }
        }
    }

    // -------------------------------------------------------------- settings

    fun isMusicEnabled(): Boolean =
        prefs?.getBoolean(KEY_MUSIC_ENABLED, DEFAULT_MUSIC_ENABLED) ?: DEFAULT_MUSIC_ENABLED

    fun isSfxEnabled(): Boolean =
        prefs?.getBoolean(KEY_SFX_ENABLED, DEFAULT_SFX_ENABLED) ?: DEFAULT_SFX_ENABLED

    fun getMusicVolume(): Float =
        prefs?.getFloat(KEY_MUSIC_VOLUME, DEFAULT_MUSIC_VOLUME) ?: DEFAULT_MUSIC_VOLUME

    fun getSfxVolume(): Float =
        prefs?.getFloat(KEY_SFX_VOLUME, DEFAULT_SFX_VOLUME) ?: DEFAULT_SFX_VOLUME

    fun setMusicEnabled(enabled: Boolean) {
        prefs?.edit()?.putBoolean(KEY_MUSIC_ENABLED, enabled)?.apply()
        if (enabled) {
            // Bring back whichever bed the current screen asked for.
            requestedTrack?.let { playBgm(it) }
        } else {
            musicWanted = false
            stopBgmInternal()
        }
    }

    fun setSfxEnabled(enabled: Boolean) {
        prefs?.edit()?.putBoolean(KEY_SFX_ENABLED, enabled)?.apply()
        if (enabled) playSfx(Sfx.CLICK)
    }

    fun setMusicVolume(volume: Float) {
        musicLevel = volume.coerceIn(0f, 1f)
        prefs?.edit()?.putFloat(KEY_MUSIC_VOLUME, musicLevel)?.apply()
        applyMusicVolume()
    }

    fun setSfxVolume(volume: Float) {
        sfxLevel = volume.coerceIn(0f, 1f)
        prefs?.edit()?.putFloat(KEY_SFX_VOLUME, sfxLevel)?.apply()
    }
}

/**
 * Implemented by activities that want a background music bed.
 *
 * The default is the menu bed, so most screens just declare `, BgmHost`; screens
 * that need their own music (the game board) override [bgmTrack].
 */
interface BgmHost {
    val bgmTrack: SoundManager.BgmTrack
        get() = SoundManager.BgmTrack.MENU
}
