import json

questions = []

def add(d, qn, a, b, c, d2, ca):
    questions.append({"category":"IS","difficulty":d,"question":qn,"option_a":a,"option_b":b,"option_c":c,"option_d":d2,"correct_answer":ca})

# EASY (35)
add('easy','What does CPU stand for?','Central Processing Unit','Computer Personal Unit','Central Program Utility','Computer Processing Unit','A')
add('easy','Which of the following is an input device?','Monitor','Printer','Keyboard','Speaker','C')
add('easy','What is the binary equivalent of the decimal number 10?','1000','1010','1100','1001','B')
add('easy','Which type of memory is volatile and loses its data when the computer is turned off?','ROM','Hard disk','RAM','Flash memory','C')
add('easy','What does LAN stand for?','Local Area Network','Large Area Network','Long Access Node','Linked Application Network','A')
add('easy','Which protocol is used to transfer web pages on the Internet?','FTP','SMTP','HTTP','TCP','C')
add('easy','What is the purpose of a primary key in a relational database?','To link two tables together','To uniquely identify each record in a table','To encrypt the database','To sort records alphabetically','B')
add('easy','Which of the following is an example of system software?','Word processor','Web browser','Operating system','Spreadsheet','C')
add('easy','What does HTML stand for?','HyperText Markup Language','High Tech Modern Language','HyperTransfer Markup Language','Home Tool Markup Language','A')
add('easy','Which of the following is a social ethical issue related to ICT?','CPU overheating','Software bugs','Privacy concerns','Network latency','C')
add('easy','What is the hexadecimal equivalent of the decimal number 15?','A','B','E','F','D')
add('easy','Which device is used to connect multiple networks together?','Switch','Hub','Router','Repeater','C')
add('easy','What type of software is used for creating and editing documents?','Spreadsheet software','Word processing software','Database software','Presentation software','B')
add('easy','Which of the following best describes artificial intelligence?','A type of computer hardware','A programming language','Computer systems that simulate human intelligence','A network protocol','C')
add('easy','What is the function of an operating system?','To browse the Internet','To manage hardware and software resources','To create spreadsheets','To design web pages','B')
add('easy','Which data type is used to store whole numbers?','String','Boolean','Integer','Character','C')
add('easy','What does DNS stand for?','Data Network Service','Domain Name System','Digital Network Security','Dynamic Name Server','B')
add('easy','Which of the following is an output device?','Mouse','Microphone','Scanner','Monitor','D')
add('easy','What is the decimal value of the binary number 1000?','4','6','8','10','C')
add('easy','Which SQL command is used to retrieve data from a database?','INSERT','DELETE','SELECT','UPDATE','C')
add('easy','What does IoT stand for?','Internet of Things','International Online Technology','Integrated Operating Terminal','Intelligent Office Tool','A')
add('easy','Which of the following is a storage device?','Keyboard','Hard disk','Monitor','Printer','B')
add('easy','What is the main purpose of data validation?','To encrypt data','To compress data','To check that data is reasonable and within acceptable limits','To delete unwanted data','C')
add('easy','Which tag is used to create a hyperlink in HTML?','<link>','<a>','<href>','<url>','B')
add('easy','What is the smallest unit of data in a computer?','Byte','Bit','Kilobyte','Nibble','B')
add('easy','Which of the following is an example of a web browser?','Microsoft Word','Google Chrome','Adobe Photoshop','Windows Media Player','B')
add('easy','What does WAN stand for?','Wide Area Network','Wireless Access Node','Web Application Network','Wide Access Network','A')
add('easy','Which control structure is used to repeat a block of code?','Sequence','Selection','Iteration','Declaration','C')
add('easy','What is the purpose of a foreign key in a database?','To uniquely identify a record','To create a link between two tables','To encrypt data','To index a table','B')
add('easy','Which of the following is NOT an example of an emerging technology?','Artificial Intelligence','Blockchain','Floppy disk','Cloud computing','C')
add('easy','What does CSS stand for in web development?','Computer Style Sheets','Creative Style System','Cascading Style Sheets','Coded Style Syntax','C')
add('easy','How many bits are there in a byte?','4','8','16','32','B')
add('easy','Which of the following is a type of cyber attack?','Firewall','Phishing','Encryption','Authentication','B')
add('easy','What is the function of a firewall?','To speed up the computer','To protect a network from unauthorized access','To store backup data','To connect to the Internet','B')
add('easy','Which of the following is an open-source operating system?','Windows','macOS','Linux','iOS','C')
add('easy','What is the purpose of normalization in a database?','To increase data redundancy','To reduce data redundancy and improve data integrity','To encrypt the database','To speed up queries','B')
print('Easy done:', len(questions))

# MEDIUM (35)
add('medium','What is the decimal value of the hexadecimal number 2F?','37','47','57','45','B')
add('medium','Which best describes the fetch-decode-execute cycle?','A method for downloading files from the Internet','The process by which a CPU processes instructions','A way to encrypt data','A database query process','B')
add('medium','In a spreadsheet what does the formula =SUM(A1:A10) do?','Finds the average of cells A1 to A10','Adds the values in cells A1 to A10','Counts the number of cells from A1 to A10','Finds the maximum value in cells A1 to A10','B')
add('medium','Which IP address is a valid private IPv4 address?','8.8.8.8','192.168.1.1','172.32.0.1','200.100.50.25','B')
add('medium','What is the ASCII code for the uppercase letter A?','48','55','65','97','C')
add('medium','Which is an example of lossless data compression?','JPEG','MP3','ZIP','MPEG','C')
add('medium','What is the output? x=5 IF x>3 THEN output A ELSE output B','A','B','5','Error','A')
add('medium','Which protocol is used for sending email?','HTTP','FTP','SMTP','SNMP','C')
add('medium','What is the main difference between RAM and ROM?','RAM is faster than ROM','RAM is volatile while ROM is non-volatile','ROM is used for input while RAM is used for output','There is no difference','B')
add('medium','Which SQL clause is used to filter records based on a condition?','ORDER BY','GROUP BY','WHERE','HAVING','C')
add('medium','What is the purpose of a subnet mask?','To encrypt network traffic','To identify the network and host portions of an IP address','To assign IP addresses automatically','To block unauthorized access','B')
add('medium','Which best describes a Trojan horse?','A virus that replicates itself','Malware disguised as legitimate software','A program that displays unwanted advertisements','A program that encrypts files for ransom','B')
add('medium','In programming what is a function?','A type of variable','A block of code that performs a specific task and can be reused','A data structure','A loop structure','B')
add('medium','What is the binary result of adding 1011 and 1101?','10110','11000','10000','11110','B')
add('medium','Which is a characteristic of a relational database?','Data is stored in a single table','Data is organized into tables with relationships between them','Data is stored in a hierarchical structure','Data cannot be queried','B')
add('medium','What does bandwidth refer to in networking?','The physical width of a network cable','The maximum data transfer rate of a network connection','The number of devices on a network','The range of a wireless network','B')
add('medium','Which HTML tag defines the most important heading?','<heading>','<h6>','<h1>','<head>','C')
add('medium','What is the purpose of data encryption?','To compress data','To convert data into a coded form to prevent unauthorized access','To delete data permanently','To organize data in a database','B')
add('medium','Which is an example of a high-level programming language?','Machine code','Assembly language','Python','Binary code','C')
add('medium','What is the role of a DNS server?','To host web pages','To translate domain names into IP addresses','To filter network traffic','To assign IP addresses dynamically','B')
add('medium','What is the purpose of a foreign key constraint?','To ensure data is encrypted','To enforce referential integrity between tables','To speed up database queries','To create a backup of the database','B')
add('medium','What is the decimal equivalent of binary 11111111?','127','255','256','128','B')
add('medium','Which network topology connects all devices to a single central cable?','Star','Ring','Bus','Mesh','C')
add('medium','In a word processor what is the purpose of Find and Replace?','To check spelling errors','To locate specific text and optionally replace it with different text','To format paragraphs','To insert images','B')
add('medium','Which is a characteristic of cloud computing?','Data must be stored on local hard drives','Resources are provided over the Internet on demand','Users must install all software locally','It cannot be accessed remotely','B')
add('medium','What is the purpose of the WHERE clause in SQL?','To sort the results','To group records','To filter records based on specified conditions','To join tables','C')
add('medium','What is a check digit used for?','Encrypting data','Compressing data','Detecting errors in data entry','Sorting data','C')
add('medium','What is the main advantage of using a DBMS?','It increases data redundancy','It reduces data redundancy and provides data security','It makes data entry slower','It eliminates the need for data backup','B')
add('medium','Which protocol operates at the transport layer of the TCP/IP model?','IP','HTTP','TCP','ARP','C')
add('medium','What is the purpose of cache memory?','To store permanent data','To provide fast access to frequently used data','To connect to the Internet','To display graphics','B')
add('medium','Which best describes machine learning?','A type of computer hardware','A programming language','A subset of AI that enables systems to learn from data','A network protocol','C')
add('medium','What is (TRUE AND FALSE) OR (TRUE AND TRUE)?','TRUE','FALSE','NULL','Error','A')
add('medium','Why use a one-to-many relationship in a database?','To encrypt data','To represent a relationship where one record relates to multiple records','To delete records','To create a backup','B')
add('medium','What is the purpose of ORDER BY in SQL?','To filter records','To sort the result set','To group records','To join tables','B')
print('Medium done:', len(questions))

# HARD (30) - first 10
add('hard','A 24-bit color image is 1024x768 pixels. Approximate file size in MB (uncompressed)?','1.5 MB','2.25 MB','3 MB','6 MB','B')
add('hard','Nested FOR loops from 1 to n with PRINT i*j. Time complexity?','O(n)','O(n log n)','O(n^2)','O(2^n)','C')
add('hard','Difference between symmetric and asymmetric encryption?','Symmetric is faster but requires secure key exchange','Asymmetric uses same key for both','Symmetric uses two different keys','Asymmetric is always faster','A')
add('hard','A table is in 3NF. What must be true?','It has no repeating groups','All non-key attributes depend on the whole primary key','All non-key attributes are functionally dependent only on the primary key','It contains no foreign keys','C')
add('hard','Sound file sampled at 44.1 kHz 16-bit stereo. Data rate per second?','88.2 KB/s','176.4 KB/s','352.8 KB/s','705.6 KB/s','B')
add('hard','Two complement representation of -5 in 8-bit?','11111010','11111011','00000101','10000101','B')
add('hard','CAP theorem in distributed systems?','Can achieve all three of consistency availability and partition tolerance','Can only achieve two out of three','Must sacrifice security for performance','Can only handle one request at a time','B')
add('hard','Output of f(4) for f(n)=n*f(n-1) if n>1 else 1?','4','10','24','120','C')
add('hard','Correct subnet mask for /26 network?','255.255.255.0','255.255.255.128','255.255.255.192','255.255.255.224','C')
add('hard','What is a consensus mechanism in blockchain?','A method for encrypting transactions','A process by which all nodes agree on the state of the ledger','A way to store data in blocks','A type of cryptocurrency','B')
print('Hard 1-10 done:', len(questions))

# HARD (30) - next 10
add('hard','SQL query to find second highest salary?','SELECT MAX(salary) FROM Employee WHERE salary NOT IN (SELECT MAX(salary) FROM Employee)','SELECT salary FROM Employee ORDER BY salary DESC LIMIT 1','SELECT TOP 1 salary FROM Employee','SELECT salary FROM Employee WHERE salary = MAX(salary)','A')
add('hard','Difference between compiler and interpreter?','Compiler translates entire program at once interpreter translates line by line','Interpreter is faster','Compiler only works with high-level languages','Interpreter produces machine code','A')
add('hard','5 TB data at 100 Mbps upload. Approximate time?','About 5 hours','About 50 hours','About 100 hours','About 500 hours','C')
add('hard','Purpose of a digital signature?','To encrypt a message','To verify the authenticity and integrity of a message','To compress a message','To hide the content of a message','B')
add('hard','What is polymorphism in OOP?','Ability to create multiple objects','Ability of different objects to respond to the same method call in different ways','Process of hiding data','Ability to inherit from multiple classes','B')
add('hard','Hexadecimal result of adding 3A7B and C584?','1000F','FFFF','100FF','10000','B')
add('hard','Man-in-the-middle attack?','Attacker floods a server with requests','Attacker secretly intercepts and possibly alters communication between two parties','Attacker guesses passwords repeatedly','Attacker sends malicious email attachments','B')
add('hard','Functional dependencies A->B B->C C->D. Candidate key?','A','B','C','D','A')
add('hard','Which is NOT a characteristic of a well-designed algorithm?','Finiteness','Ambiguity','Definiteness','Effectiveness','B')
add('hard','OSI layer where a router operates?','Physical layer','Data link layer','Network layer','Transport layer','C')
print('Hard 11-20 done:', len(questions))

# HARD (30) - last 10
add('hard','Purpose of ACID properties?','To ensure data compression','To ensure reliable processing of database transactions','To encrypt database contents','To speed up query processing','B')
add('hard','Difference between deep learning and traditional machine learning?','Deep learning requires less data','Deep learning uses neural networks with multiple layers','Deep learning does not require training','Deep learning is only for text processing','B')
add('hard','Class C network needs 6 subnets. Minimum subnet mask?','255.255.255.192','255.255.255.224','255.255.255.240','255.255.255.248','B')
add('hard','Time complexity of binary search on sorted array of n elements?','O(1)','O(log n)','O(n)','O(n log n)','B')
add('hard','Purpose of a VPN?','To increase Internet speed','To create a secure connection over a public network','To block all incoming connections','To assign IP addresses','B')
add('hard','Creative Commons licensing allows?','Complete restriction of all uses','Creators to specify how others may use their work','Automatic copyright transfer to public','Unlimited commercial use without attribution','B')
add('hard','console.log(typeof null) in JavaScript?','null','undefined','object','number','C')
add('hard','Purpose of data mining?','Deleting data from databases','Discovering patterns and knowledge from large datasets','Encrypting data for security','Backing up data to the cloud','B')
add('hard','System uses 20 address lines. Maximum memory capacity?','512 KB','1 MB','2 MB','4 MB','B')
add('hard','Key difference between TCP and UDP?','TCP is connectionless while UDP is connection-oriented','TCP provides reliable delivery while UDP does not guarantee delivery','UDP is slower than TCP','TCP does not use port numbers','B')
print('Hard 21-30 done:', len(questions))

# HARD (30) - remaining 70 questions as additional hard questions to reach 100 total
add('hard','Most environmentally responsible e-waste approach?','Landfill disposal','Incineration','Recycling and proper disposal of electronic components','Exporting to other countries','C')
add('hard','Purpose of GROUP BY in SQL?','To filter rows','To sort results','To group rows with same values in specified columns','To join tables','C')
add('hard','Abstraction in OOP?','Showing all implementation details','Hiding complex implementation details and showing only essential features','Creating multiple copies of an object','Converting data from one type to another','B')
add('hard','SELECT COUNT(*) FROM Students WHERE grade IS NULL returns?','Total number of students','Number of students with no grade assigned','Number of students with grade 0','An error','B')
add('hard','Distributed database?','A database stored on a single server','A database where data is stored across multiple physical locations','A database that cannot be queried','A database that only stores text data','B')
add('hard','Purpose of a DMZ?','To isolate internal network from external networks','To host public-facing services while protecting the internal network','To encrypt all network traffic','To block all incoming connections','B')
add('hard','Purpose of regular expressions?','To perform mathematical calculations','To define patterns for matching and manipulating text','To create database tables','To encrypt data','B')
add('hard','Difference between 1NF and 2NF?','There is no difference','2NF requires all non-key attributes depend on the entire primary key','1NF allows repeating groups','2NF allows partial dependencies','B')
add('hard','Microservices architecture?','A single large application','An approach where an application is built as a collection of small independent services','A type of database','A network protocol','B')
add('hard','Purpose of a disaster recovery plan?','To prevent all disasters','To ensure business continuity and restore IT systems after a disaster','To replace all hardware annually','To train employees in programming','B')
print('Hard 31-40 done:', len(questions))

add('hard','Difference between a view and a table in SQL?','They are the same','A view is a virtual table based on a query; a table stores actual data','A view can only store numeric data','A table cannot be queried','B')
add('hard','Purpose of UNIQUE constraint in SQL?','To ensure a column cannot be empty','To ensure all values in a column are distinct','To create a primary key','To link two tables','B')
add('hard','Data warehousing?','Storing data in a single file','Collecting and managing data from various sources for analysis and reporting','Deleting old data','Encrypting all data','B')
add('hard','Pass by value vs pass by reference?','They are the same','Pass by value copies the data; pass by reference passes the memory address','Pass by reference is only used in Python','Pass by value is always faster','B')
add('hard','Purpose of a CDN?','To create web content','To distribute web content to users based on geographic location','To encrypt web traffic','To block malicious websites','B')
add('hard','Python: 7 // 3 + 7 % 3 = ?','3','4','2','5','A')
add('hard','Software development life cycle (SDLC)?','The time it takes to write a program','A structured process for planning creating testing and deploying software','The lifespan of a computer','A type of programming language','B')
add('hard','Purpose of an index in database design?','To store backup data','To speed up data retrieval operations on a table','To encrypt table data','To create relationships between tables','B')
add('hard','Difference between HTTP and HTTPS?','They are the same protocol','HTTPS uses encryption (SSL/TLS) while HTTP does not','HTTP is faster in all cases','HTTPS is only used for email','B')
add('hard','Purpose of CHECK constraint in SQL?','To verify database connectivity','To ensure values in a column satisfy a specified condition','To create a primary key','To sort query results','B')
print('Hard 41-50 done:', len(questions))

add('hard','Data dictionary in database systems?','A list of all passwords','A centralized repository of information about data such as meaning and relationships','A tool for creating user interfaces','A type of database backup','B')
add('hard','Purpose of ARP protocol?','To assign IP addresses','To map IP addresses to MAC addresses','To encrypt network traffic','To route packets between networks','B')
add('hard','Encapsulation in OOP?','Creating multiple objects','Bundling data and methods together and restricting direct access to internal state','Inheriting from multiple classes','Converting data types','B')
add('hard','Purpose of DEFAULT constraint in SQL?','To set a default value for a column when no value is specified','To create a primary key','To link tables','To sort results','A')
add('hard','Data mart?','A place to buy data','A subset of a data warehouse focused on a specific business area','A type of database virus','A tool for creating databases','B')
add('hard','Gantt chart used for?','To write code','To visualize project schedules and track progress','To design databases','To test software','B')
add('hard','Difference between trigger and stored procedure?','They are the same','A trigger is automatically executed in response to events; a stored procedure must be explicitly called','A stored procedure is faster','A trigger can only be used for SELECT','B')
add('hard','Purpose of COMMIT in SQL?','To undo a transaction','To permanently save all changes made during a transaction','To create a new table','To delete records','B')
add('hard','Data lake?','A small database','A large storage repository that holds raw data in its native format','A type of data visualization','A network protocol','B')
add('hard','Purpose of AJAX?','To style web pages','To send and receive data from a server asynchronously without reloading the page','To create databases','To validate user input','B')
print('Hard 51-60 done:', len(questions))

add('hard','RDBMS?','A system that stores data in files','A system that manages data in tables with defined relationships','A system that only stores images','A system that cannot be queried','B')
add('hard','Purpose of ROLLBACK in SQL?','To save changes permanently','To undo changes made during a transaction','To create a new database','To delete a table','B')
add('hard','Data governance?','Creating databases','The overall management of data availability usability integrity and security','Writing SQL queries','Designing user interfaces','B')
add('hard','Black-box vs white-box testing?','They are the same','Black-box tests functionality without knowing internal code; white-box tests internal structures','White-box is always better','Black-box requires access to source code','B')
add('hard','Purpose of a surrogate key?','A natural key derived from business data','An artificial key with no business meaning used to uniquely identify records','A key used for encryption','A key that links two tables','B')
add('hard','SELECT dept COUNT(*) FROM employees GROUP BY dept HAVING COUNT(*) > 5 returns?','All departments','Departments with more than 5 employees','First 5 employees','An error','B')
add('hard','Data pipeline?','A physical cable for data transfer','A set of data processing elements connected in series for automated data flow','A type of database','A network protocol','B')
add('hard','IaaS vs PaaS vs SaaS?','They are the same','IaaS provides infrastructure; PaaS provides a platform; SaaS provides software applications','SaaS is most complex','IaaS is only for small businesses','B')
add('hard','Purpose of a database view?','To physically store data','To provide a virtual table based on a stored query for security and simplicity','To create indexes','To backup data','B')
add('hard','Purpose of LIMIT in SQL?','To filter records','To restrict the number of rows returned by a query','To sort results','To group records','B')
print('Hard 61-70 done:', len(questions))

add('hard','Neural network?','A type of computer hardware','A computing system inspired by biological neural networks used in machine learning','A network protocol','A database structure','B')
add('hard','Principle of least privilege?','Giving all users full access','Granting users only the minimum access necessary to perform their tasks','Removing all access controls','Using same password for all accounts','B')
add('hard','Full outer join vs inner join?','They are the same','Full outer join returns all records from both tables; inner join returns only matching records','Inner join is always faster','Full outer join only returns matching records','B')
add('hard','Purpose of COALESCE in SQL?','To count records','To return the first non-null value from a list of expressions','To sort results','To create a new table','B')
add('hard','Data warehouse architecture?','A single database for all purposes','A system designed for analytical processing with integrated subject-oriented data','A type of network topology','A programming paradigm','B')
add('hard','Purpose of UML diagram?','To write code','To visually represent a system structure and behavior','To test software','To deploy applications','B')
add('hard','Data deduplication?','Creating multiple copies of data','Eliminating duplicate copies of data to save storage space','Encrypting data','Sorting data','B')
add('hard','Purpose of EXISTS in SQL?','To check if a table exists','To test whether a subquery returns any rows','To count records','To sort results','B')
add('hard','RESTful API?','A type of database','An API that follows REST architectural principles using HTTP methods','A programming language','A network protocol','B')
add('hard','I in ACID stands for?','Integration','Isolation','Integrity','Indexing','B')
print('Hard 71-80 done:', len(questions))

add('hard','Purpose of a database trigger?','To manually execute queries','To automatically execute a procedure in response to specific events on a table','To create indexes','To backup data','B')
add('hard','1111 XOR 1010 = ?','0101','1111','0000','1010','A')
add('hard','Data governance framework?','A programming language','A set of policies and procedures for managing data assets','A type of database','A network protocol','B')
add('hard','Purpose of DOM?','To style web pages','To provide a programming interface for dynamically accessing and modifying web page content','To create databases','To encrypt data','B')
add('hard','Horizontal vs vertical scaling?','They are the same','Horizontal scaling adds more machines; vertical scaling adds more resources to existing machines','Vertical is always better','Horizontal only works for databases','B')
add('hard','Purpose of CASE in SQL?','To create a new table','To perform conditional logic in queries','To delete records','To create indexes','B')
add('hard','Data mesh?','A type of network cable','A decentralized approach to data architecture where domain teams own their data','A database management system','A programming language','B')
add('hard','Purpose of MFA?','To use multiple passwords','To require multiple forms of verification before granting access','To encrypt data','To create backups','B')
add('hard','Purpose of a database schema?','To store user data','To define the structure and organization of a database','To create backups','To encrypt data','B')
add('hard','SELECT NULL = NULL returns?','TRUE','FALSE','NULL','Error','C')
print('Hard 81-90 done:', len(questions))

add('hard','Data fabric?','A type of clothing material','An architecture that provides a unified view of data across multiple environments','A programming language','A network protocol','B')
add('hard','Purpose of CI?','To deploy software to production','To automatically build and test code changes frequently','To write documentation','To create user interfaces','B')
add('hard','Clustered vs non-clustered index?','They are the same','A clustered index determines the physical order of data; a non-clustered index does not','Non-clustered is always faster','Clustered can only be on primary keys','B')
add('hard','Purpose of UNION in SQL?','To join tables','To combine the result sets of two or more SELECT statements','To create a new table','To delete records','B')
add('hard','Data catalog?','A shopping catalog for data','A metadata management tool that helps organizations find and understand their data','A type of database','A programming language','B')
add('hard','Purpose of an SLA?','To write code','To define the expected level of service between a provider and a customer','To design databases','To test software','B')
add('hard','Data lineage?','A family tree of databases','The tracking of data flow from source to destination through transformations','A type of encryption','A network protocol','B')
add('hard','Purpose of SAVEPOINT in SQL?','To create a backup','To set a point within a transaction to which you can later roll back','To commit a transaction','To create a new table','B')
add('hard','Data quality framework?','A programming language','A set of practices to ensure data is accurate complete and reliable','A type of database','A network protocol','B')
add('hard','Strong entity vs weak entity?','They are the same','A strong entity has its own primary key; a weak entity depends on another entity for identification','Weak entity is always faster','Strong entity cannot have relationships','B')
print('Hard 91-100 done:', len(questions))

# Output
print('Total questions:', len(questions))
easy = len([q for q in questions if q['difficulty']=='easy'])
medium = len([q for q in questions if q['difficulty']=='medium'])
hard = len([q for q in questions if q['difficulty']=='hard'])
print(f'Easy: {easy}, Medium: {medium}, Hard: {hard}')

with open('/d/dev/millionaire/questions.json', 'w') as f:
    json.dump(questions, f, indent=2, ensure_ascii=False)
print('Written to questions.json')
