const fs = require('fs');

const chinHistory = [
  { category: 'Chin History', difficulty: 'easy', question: 'Which dynasty is traditionally regarded as the first dynasty in Chinese history?', option_a: 'Shang dynasty (商朝)', option_b: 'Xia dynasty (夏朝)', option_c: 'Zhou dynasty (周朝)', option_d: 'Qin dynasty (秦朝)', correct_answer: 'B' },
  { category: 'Chin History', difficulty: 'easy', question: 'Who was the founder of Confucianism?', option_a: 'Laozi (老子)', option_b: 'Mencius (孟子)', option_c: 'Confucius (孔子)', option_d: 'Zhuangzi (莊子)', correct_answer: 'C' },
  { category: 'Chin History', difficulty: 'easy', question: 'Which school of thought emphasised rule by strict laws and harsh punishments?', option_a: 'Confucianism (儒家)', option_b: 'Daoism (道家)', option_c: 'Mohism (墨家)', option_d: 'Legalism (法家)', correct_answer: 'D' },
  { category: 'Chin History', difficulty: 'easy', question: 'The Mandate of Heaven (天命) theory was first used to justify the overthrow of which dynasty?', option_a: 'Xia dynasty (夏朝)', option_b: 'Shang dynasty (商朝)', option_c: 'Zhou dynasty (周朝)', option_d: 'Qin dynasty (秦朝)', correct_answer: 'B' },
  { category: 'Chin History', difficulty: 'easy', question: 'Who wrote the Dao De Jing (道德經), the foundational text of Daoism?', option_a: 'Confucius (孔子)', option_b: 'Mencius (孟子)', option_c: 'Laozi (老子)', option_d: 'Han Fei (韓非)', correct_answer: 'C' },
  { category: 'Chin History', difficulty: 'easy', question: 'Which philosophy did Emperor Wu of Han (漢武帝) adopt as the state ideology?', option_a: 'Legalism (法家)', option_b: 'Daoism (道家)', option_c: 'Confucianism (儒學)', option_d: 'Buddhism (佛教)', correct_answer: 'C' },
  { category: 'Chin History', difficulty: 'easy', question: 'Who was the first emperor to unify China?', option_a: 'Emperor Gaozu of Han (漢高祖)', option_b: 'Qin Shi Huang (秦始皇)', option_c: 'King Wu of Zhou (周武王)', option_d: 'Emperor Wu of Han (漢武帝)', correct_answer: 'B' },
  { category: 'Chin History', difficulty: 'easy', question: 'The Silk Road was opened during the reign of which emperor?', option_a: 'Qin Shi Huang (秦始皇)', option_b: 'Emperor Gaozu of Han (漢高祖)', option_c: 'Emperor Wu of Han (漢武帝)', option_d: 'Emperor Wen of Sui (隋文帝)', correct_answer: 'C' },
  { category: 'Chin History', difficulty: 'easy', question: 'What was the capital of the Qin dynasty?', option_a: 'Chang\'an (長安)', option_b: 'Luoyang (洛陽)', option_c: 'Xianyang (咸陽)', option_d: 'Beijing (北京)', correct_answer: 'C' },
  { category: 'Chin History', difficulty: 'easy', question: 'Zhang Qian (張騫) was sent on a diplomatic mission to the Western Regions (西域) by which emperor?', option_a: 'Qin Shi Huang (秦始皇)', option_b: 'Emperor Gaozu of Han (漢高祖)', option_c: 'Emperor Wen of Han (漢文帝)', option_d: 'Emperor Wu of Han (漢武帝)', correct_answer: 'D' },
  { category: 'Chin History', difficulty: 'easy', question: 'Buddhism was introduced to China during which dynasty?', option_a: 'Qin dynasty (秦朝)', option_b: 'Han dynasty (漢朝)', option_c: 'Wei dynasty (魏朝)', option_d: 'Jin dynasty (晉朝)', correct_answer: 'B' },
  { category: 'Chin History', difficulty: 'easy', question: 'The Nine-rank system (九品中正制) was used during the Wei-Jin period primarily to:', option_a: 'Rank Buddhist monks', option_b: 'Select government officials', option_c: 'Classify land ownership', option_d: 'Organise the military', correct_answer: 'B' },
  { category: 'Chin History', difficulty: 'easy', question: 'Which was a major characteristic of the Wei-Jin-Southern-and-Northern-Dynasties period?', option_a: 'Strong centralised bureaucracy', option_b: 'Rise of aristocratic families (門閥世族)', option_c: 'Widespread use of imperial examinations', option_d: 'Legalism as state ideology', correct_answer: 'B' },
  { category: 'Chin History', difficulty: 'easy', question: 'The Grand Canal (大運河) was mainly built during which dynasty?', option_a: 'Qin dynasty (秦朝)', option_b: 'Han dynasty (漢朝)', option_c: 'Sui dynasty (隋朝)', option_d: 'Tang dynasty (唐朝)', correct_answer: 'C' },
  { category: 'Chin History', difficulty: 'easy', question: 'The Reign of Zhenguan (貞觀之治) was the prosperous period under which Tang emperor?', option_a: 'Emperor Yang of Sui (隋煬帝)', option_b: 'Emperor Taizong of Tang (唐太宗)', option_c: 'Emperor Xuanzong of Tang (唐玄宗)', option_d: 'Empress Wu Zetian (武則天)', correct_answer: 'B' },
  { category: 'Chin History', difficulty: 'easy', question: 'The An Lushan Rebellion (安史之亂) took place during which dynasty?', option_a: 'Sui dynasty (隋朝)', option_b: 'Tang dynasty (唐朝)', option_c: 'Han dynasty (漢朝)', option_d: 'Song dynasty (宋朝)', correct_answer: 'B' },
  { category: 'Chin History', difficulty: 'easy', question: 'Who was the only female emperor in Chinese history?', option_a: 'Empress Dowager Cixi (慈禧太后)', option_b: 'Empress Lü (呂后)', option_c: 'Wu Zetian (武則天)', option_d: 'Empress He (何后)', correct_answer: 'C' },
  { category: 'Chin History', difficulty: 'easy', question: 'The Reign of Kaiyuan (開元之治) was the golden age under which Tang emperor?', option_a: 'Emperor Taizong (唐太宗)', option_b: 'Emperor Gaozong (唐高宗)', option_c: 'Emperor Xuanzong (唐玄宗)', option_d: 'Emperor Zhongzong (唐中宗)', correct_answer: 'C' },
  { category: 'Chin History', difficulty: 'easy', question: 'Neo-Confucianism (理學) was developed and flourished during which dynasty?', option_a: 'Tang dynasty (唐朝)', option_b: 'Song dynasty (宋朝)', option_c: 'Yuan dynasty (元朝)', option_d: 'Ming dynasty (明朝)', correct_answer: 'B' },
  { category: 'Chin History', difficulty: 'easy', question: 'Wang Anshi\'s Reforms (王安石變法) took place during which dynasty?', option_a: 'Tang dynasty (唐朝)', option_b: 'Song dynasty (宋朝)', option_c: 'Yuan dynasty (元朝)', option_d: 'Ming dynasty (明朝)', correct_answer: 'B' },
  { category: 'Chin History', difficulty: 'easy', question: 'The Yuan dynasty was founded by which ruler?', option_a: 'Genghis Khan (成吉思汗)', option_b: 'Kublai Khan (忽必烈)', option_c: 'Hongwu Emperor (洪武帝)', option_d: 'Emperor Taizong of Tang (唐太宗)', correct_answer: 'B' },
  { category: 'Chin History', difficulty: 'easy', question: 'Marco Polo visited China during the reign of which ruler?', option_a: 'Qin Shi Huang (秦始皇)', option_b: 'Emperor Wu of Han (漢武帝)', option_c: 'Kublai Khan (忽必烈)', option_d: 'Hongwu Emperor (洪武帝)', correct_answer: 'C' },
  { category: 'Chin History', difficulty: 'easy', question: 'Zheng He\'s maritime expeditions (鄭和下西洋) took place during which dynasty?', option_a: 'Song dynasty (宋朝)', option_b: 'Yuan dynasty (元朝)', option_c: 'Ming dynasty (明朝)', option_d: 'Qing dynasty (清朝)', correct_answer: 'C' },
  { category: 'Chin History', difficulty: 'easy', question: 'The Prosperous Era of Kangxi, Yongzheng and Qianlong (康乾盛世) refers to the height of which dynasty?', option_a: 'Early Ming (明初)', option_b: 'Early Qing (清初)', option_c: 'High Tang (盛唐)', option_d: 'Northern Song (北宋)', correct_answer: 'B' },
  { category: 'Chin History', difficulty: 'easy', question: 'The First Opium War (鴉片戰爭) broke out in which year?', option_a: '1840', option_b: '1860', option_c: '1894', option_d: '1900', correct_answer: 'A' },
  { category: 'Chin History', difficulty: 'easy', question: 'The Self-Strengthening Movement (自強運動) aimed to:', option_a: 'Restore the imperial examination system', option_b: 'Learn Western technology while preserving Chinese values', option_c: 'Abolish Confucianism entirely', option_d: 'Establish a democratic republic', correct_answer: 'B' },
  { category: 'Chin History', difficulty: 'easy', question: 'The Hundred Days\' Reform (百日維新) took place in which year?', option_a: '1840', option_b: '1860', option_c: '1898', option_d: '1911', correct_answer: 'C' },
  { category: 'Chin History', difficulty: 'easy', question: 'The Xinhai Revolution (辛亥革命) took place in which year?', option_a: '1898', option_b: '1901', option_c: '1911', option_d: '1919', correct_answer: 'C' },
  { category: 'Chin History', difficulty: 'easy', question: 'The May Fourth Movement (五四運動) occurred in which year?', option_a: '1911', option_b: '1919', option_c: '1925', option_d: '1931', correct_answer: 'B' },
  { category: 'Chin History', difficulty: 'easy', question: 'The Northern Expedition (北伐) was led by which leader?', option_a: 'Sun Yat-sen (孫中山)', option_b: 'Yuan Shikai (袁世凱)', option_c: 'Chiang Kai-shek (蔣介石)', option_d: 'Mao Zedong (毛澤東)', correct_answer: 'C' },
  { category: 'Chin History', difficulty: 'easy', question: 'The War of Resistance against Japan (抗日戰爭) lasted from:', option_a: '1911 to 1919', option_b: '1927 to 1937', option_c: '1937 to 1945', option_d: '1945 to 1949', correct_answer: 'C' },
  { category: 'Chin History', difficulty: 'easy', question: 'The People\'s Republic of China was founded in which year?', option_a: '1945', option_b: '1949', option_c: '1950', option_d: '1958', correct_answer: 'B' },
  { category: 'Chin History', difficulty: 'easy', question: 'The Great Leap Forward (大躍進) took place during which period?', option_a: '1949 to 1952', option_b: '1958 to 1961', option_c: '1966 to 1976', option_d: '1978 to 1984', correct_answer: 'B' },
  { category: 'Chin History', difficulty: 'easy', question: 'Hong Kong Island was ceded to Britain under which treaty?', option_a: 'Treaty of Nanking (南京條約)', option_b: 'Convention of Beijing (北京條約)', option_c: 'Treaty of Tientsin (天津條約)', option_d: 'Treaty of Shimonoseki (馬關條約)', correct_answer: 'A' },
  { category: 'Chin History', difficulty: 'easy', question: 'The Sino-British Joint Declaration (中英聯合聲明) was signed in which year?', option_a: '1982', option_b: '1984', option_c: '1997', option_d: '1990', correct_answer: 'B' }
];

fs.writeFileSync('D:/dev/millionaire/chin_history_questions.js', JSON.stringify(chinHistory, null, 2));
console.log('Saved ' + chinHistory.length + ' Chin History questions');
