package com.millionaireapp.audio

import android.content.Context
import android.content.res.AssetFileDescriptor
import android.media.AudioAttributes
import android.media.AudioFocusRequest
import android.media.AudioManager
import android.media.MediaPlayer
import android.media.SoundPool
import android.os.Build
import android.util.Log
import com.facebook.react.bridge.LifecycleEventListener
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import com.facebook.react.bridge.ReadableArray
import com.facebook.react.bridge.UiThreadUtil
import com.millionaireapp.R

/**
 * Native audio engine: looping background music plus low-latency sound effects.
 *
 * - Sound effects are preloaded into a [SoundPool] so they fire instantly on tap.
 * - Music plays through a looping [MediaPlayer] (one track at a time).
 * - Music automatically pauses when the app goes to the background and resumes on
 *   return, and it politely ducks/pauses when another app takes audio focus.
 *
 * The JS side ([src/audio/audioManager.ts]) owns the user's preferences (on/off,
 * volume) and the choice of track; this module only renders what it is told to.
 * Every method is fire-and-forget, so a missing or slow audio device can never
 * block the UI thread.
 */
class SoundModule(private val reactContext: ReactApplicationContext) :
    ReactContextBaseJavaModule(reactContext),
    LifecycleEventListener,
    AudioManager.OnAudioFocusChangeListener {

  companion object {
    const val NAME = "SoundModule"
    private const val TAG = "SoundModule"

    /** Music volume multiplier while another app is talking over us. */
    private const val DUCK_FACTOR = 0.25f
    private const val MAX_SFX_STREAMS = 4

    /**
     * Sound names exposed to JS -> packaged raw resources.
     *
     * These files are generated by `node tools/generate-audio.js`; add new entries
     * here (and regenerate) when the JS sound table grows.
     */
    private val RAW_RESOURCES: Map<String, Int> =
        mapOf(
            "sfx_click" to R.raw.sfx_click,
            "sfx_lock" to R.raw.sfx_lock,
            "sfx_suspense" to R.raw.sfx_suspense,
            "sfx_correct" to R.raw.sfx_correct,
            "sfx_wrong" to R.raw.sfx_wrong,
            "sfx_lifeline" to R.raw.sfx_lifeline,
            "sfx_win" to R.raw.sfx_win,
            "sfx_lose" to R.raw.sfx_lose,
            "bgm_menu" to R.raw.bgm_menu,
            "bgm_game" to R.raw.bgm_game,
        )
  }

  private val audioAttributes: AudioAttributes =
      AudioAttributes.Builder()
          .setUsage(AudioAttributes.USAGE_GAME)
          .setContentType(AudioAttributes.CONTENT_TYPE_MUSIC)
          .build()

  private val audioManager: AudioManager? =
      reactContext.getSystemService(Context.AUDIO_SERVICE) as? AudioManager

  private val soundPool: SoundPool =
      SoundPool.Builder()
          .setMaxStreams(MAX_SFX_STREAMS)
          .setAudioAttributes(audioAttributes)
          .build()

  /** resource name -> SoundPool sample id */
  private val sampleIds = HashMap<String, Int>()

  /** SoundPool sample id -> resource name */
  private val sampleNames = HashMap<Int, String>()

  /** Sample ids that finished loading and are ready to play. */
  private val loadedSamples = HashSet<Int>()

  /** Plays requested before their sample finished loading: name -> volume. */
  private val pendingPlays = HashMap<String, Float>()

  private var sfxLevel = 1.0f
  private var bgmLevel = 0.6f

  private var bgmPlayer: MediaPlayer? = null
  private var bgmName: String? = null

  /** Whether music should be sounding; cleared by pauseBgm/stopBgm. */
  private var bgmWanted = false

  /** True while the host activity is paused (app in background). */
  private var hostPaused = false

  private var audioFocusHeld = false
  private var focusRequest: AudioFocusRequest? = null
  private var ducked = false

  @Volatile private var released = false

  init {
    soundPool.setOnLoadCompleteListener { _, sampleId, status ->
      if (status == 0) {
        loadedSamples.add(sampleId)
        val name = sampleNames[sampleId]
        val queuedVolume = name?.let { pendingPlays.remove(it) }
        if (name != null && queuedVolume != null) {
          // The sound was requested while it was still decoding: play it now.
          playSample(sampleId, queuedVolume)
        }
      } else {
        Log.w(TAG, "SoundPool failed to load ${sampleNames[sampleId]} (status=$status)")
      }
    }
    reactContext.addLifecycleEventListener(this)
  }

  override fun getName(): String = NAME

  // ------------------------------------------------------------------ effects

  /** Decode sound effects ahead of time so the first tap is not silent. */
  @ReactMethod
  fun preloadSfx(names: ReadableArray) {
    for (i in 0 until names.size()) {
      names.getString(i)?.let { ensureSampleLoaded(it) }
    }
  }

  /** Fire a one-shot sound effect. [volume] is 0..1 and scales the user's level. */
  @ReactMethod
  fun playSfx(name: String, volume: Double) {
    if (released) return
    val level = (sfxLevel * volume.toFloat()).coerceIn(0f, 1f)
    if (level <= 0f) return
    val sampleId = ensureSampleLoaded(name) ?: return
    if (loadedSamples.contains(sampleId)) {
      playSample(sampleId, level)
    } else {
      pendingPlays[name] = level
    }
  }

  /** 0..1 master level applied to every subsequent effect. */
  @ReactMethod
  fun setSfxVolume(volume: Double) {
    sfxLevel = volume.toFloat().coerceIn(0f, 1f)
  }

  private fun ensureSampleLoaded(name: String): Int? {
    if (released) return null
    sampleIds[name]?.let {
      return it
    }
    val resId = RAW_RESOURCES[name]
    if (resId == null) {
      Log.w(TAG, "Unknown sound effect: $name")
      return null
    }
    val id = soundPool.load(reactContext, resId, 1)
    if (id == 0) {
      Log.w(TAG, "SoundPool rejected $name")
      return null
    }
    sampleIds[name] = id
    sampleNames[id] = name
    return id
  }

  private fun playSample(sampleId: Int, volume: Float) {
    soundPool.play(sampleId, volume, volume, 1, 0, 1.0f)
  }

  // ------------------------------------------------------------------- music

  /**
   * Start (or switch to) a looping music track. Calling this again with the track
   * that is already loaded resumes it instead of restarting from the beginning.
   */
  @ReactMethod
  fun playBgm(name: String, volume: Double, loop: Boolean) {
    bgmLevel = volume.toFloat().coerceIn(0f, 1f)
    UiThreadUtil.runOnUiThread {
      if (released) return@runOnUiThread

      if (bgmPlayer != null && bgmName == name) {
        bgmWanted = true
        applyBgmVolume()
        startBgmIfPossible()
        return@runOnUiThread
      }

      releaseBgmPlayer()
      val resId = RAW_RESOURCES[name]
      if (resId == null) {
        Log.w(TAG, "Unknown music track: $name")
        return@runOnUiThread
      }
      val player = createPlayer(resId) ?: return@runOnUiThread
      player.isLooping = loop
      bgmPlayer = player
      bgmName = name
      bgmWanted = true
      applyBgmVolume()
      startBgmIfPossible()
    }
  }

  /** Stop music and unload the track (used when the player turns music off). */
  @ReactMethod
  fun stopBgm() {
    UiThreadUtil.runOnUiThread {
      bgmWanted = false
      releaseBgmPlayer()
      abandonAudioFocus()
    }
  }

  /** Pause without forgetting the track, so [resumeBgm] can pick it up again. */
  @ReactMethod
  fun pauseBgm() {
    UiThreadUtil.runOnUiThread {
      bgmWanted = false
      bgmPlayer?.let { if (it.isPlaying) it.pause() }
    }
  }

  @ReactMethod
  fun resumeBgm() {
    UiThreadUtil.runOnUiThread {
      bgmWanted = true
      startBgmIfPossible()
    }
  }

  @ReactMethod
  fun setBgmVolume(volume: Double) {
    bgmLevel = volume.toFloat().coerceIn(0f, 1f)
    UiThreadUtil.runOnUiThread { applyBgmVolume() }
  }

  private fun createPlayer(resId: Int): MediaPlayer? {
    // Prefer the file-descriptor path: it keeps the compressed-in-APK resource
    // streamable (see `androidResources { noCompress += "wav" }` in build.gradle).
    try {
      val player = MediaPlayer()
      player.setAudioAttributes(audioAttributes)
      val afd: AssetFileDescriptor? = reactContext.resources.openRawResourceFd(resId)
      if (afd != null) {
        afd.use { player.setDataSource(it.fileDescriptor, it.startOffset, it.length) }
        player.prepare()
      } else {
        player.setDataSource(
            reactContext,
            android.net.Uri.parse("android.resource://${reactContext.packageName}/$resId"),
        )
        player.prepare()
      }
      player.setOnErrorListener { _, what, extra ->
        Log.w(TAG, "MediaPlayer error (what=$what extra=$extra)")
        true
      }
      return player
    } catch (e: Exception) {
      Log.w(TAG, "Could not prepare music track", e)
      return null
    }
  }

  private fun startBgmIfPossible() {
    val player = bgmPlayer ?: return
    if (!bgmWanted || hostPaused) return
    if (!requestAudioFocus()) return
    if (!player.isPlaying) {
      try {
        player.start()
      } catch (e: IllegalStateException) {
        Log.w(TAG, "Could not start music", e)
      }
    }
  }

  private fun applyBgmVolume() {
    val level = if (ducked) bgmLevel * DUCK_FACTOR else bgmLevel
    bgmPlayer?.setVolume(level, level)
  }

  private fun releaseBgmPlayer() {
    bgmPlayer?.let { player ->
      try {
        if (player.isPlaying) player.stop()
      } catch (_: IllegalStateException) {
        // already stopped/released - nothing to do
      }
      player.reset()
      player.release()
    }
    bgmPlayer = null
    bgmName = null
  }

  // ------------------------------------------------------------- audio focus

  private fun requestAudioFocus(): Boolean {
    if (audioFocusHeld) return true
    val manager = audioManager ?: return true // no audio service: just play
    val granted =
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
          val request =
              focusRequest
                  ?: AudioFocusRequest.Builder(AudioManager.AUDIOFOCUS_GAIN)
                      .setAudioAttributes(audioAttributes)
                      .setOnAudioFocusChangeListener(this)
                      .setWillPauseWhenDucked(false)
                      .build()
                      .also { focusRequest = it }
          manager.requestAudioFocus(request) == AudioManager.AUDIOFOCUS_REQUEST_GRANTED
        } else {
          @Suppress("DEPRECATION")
          manager.requestAudioFocus(
              this,
              AudioManager.STREAM_MUSIC,
              AudioManager.AUDIOFOCUS_GAIN,
          ) == AudioManager.AUDIOFOCUS_REQUEST_GRANTED
        }
    audioFocusHeld = granted
    if (!granted) Log.w(TAG, "Audio focus denied; music stays paused")
    return granted
  }

  private fun abandonAudioFocus() {
    if (!audioFocusHeld) return
    val manager = audioManager ?: return
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
      focusRequest?.let { manager.abandonAudioFocusRequest(it) }
    } else {
      @Suppress("DEPRECATION")
      manager.abandonAudioFocus(this)
    }
    audioFocusHeld = false
  }

  override fun onAudioFocusChange(focusChange: Int) {
    when (focusChange) {
      AudioManager.AUDIOFOCUS_GAIN -> {
        audioFocusHeld = true
        ducked = false
        applyBgmVolume()
        UiThreadUtil.runOnUiThread { startBgmIfPossible() }
      }
      AudioManager.AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK -> {
        ducked = true
        applyBgmVolume()
      }
      AudioManager.AUDIOFOCUS_LOSS_TRANSIENT,
      AudioManager.AUDIOFOCUS_LOSS -> {
        // Keep bgmWanted: the next resume (or focus gain) brings the music back.
        audioFocusHeld = false
        ducked = false
        bgmPlayer?.let { if (it.isPlaying) it.pause() }
      }
    }
  }

  // --------------------------------------------------------------- lifecycle

  override fun onHostResume() {
    hostPaused = false
    UiThreadUtil.runOnUiThread { startBgmIfPossible() }
  }

  override fun onHostPause() {
    hostPaused = true
    UiThreadUtil.runOnUiThread { bgmPlayer?.let { if (it.isPlaying) it.pause() } }
  }

  override fun onHostDestroy() {
    UiThreadUtil.runOnUiThread { shutdown() }
  }

  /**
   * Release everything. Called when the React instance goes away, so a dev reload
   * or app shutdown never leaves a decoder or audio-focus request behind.
   */
  override fun invalidate() {
    shutdown()
    super.invalidate()
  }

  private fun shutdown() {
    if (released) return
    released = true
    bgmWanted = false
    releaseBgmPlayer()
    abandonAudioFocus()
    soundPool.release()
    sampleIds.clear()
    sampleNames.clear()
    loadedSamples.clear()
    pendingPlays.clear()
    reactContext.removeLifecycleEventListener(this)
  }
}
